name: Build Project

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: "Setup Python and PlatformIO cache"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: '${{ runner.os }}-pio'
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: "Install PlatformIO Core"
        run: pip install -U platformio

      - name: "Build Project"
        run: pio run